packages: []

catalogs:
  build:
    '@nuxt/devtools': ^3.1.0
    '@nuxt/eslint': ^1.10.0
    '@nuxt/kit': ^4.2.1
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.5.5
    '@unocss/nuxt': ^66.5.5
    '@vueuse/nuxt': ^14.0.0
    nuxt: ^4.2.1
    unocss: ^66.5.5
    unplugin: ^2.3.10
    vite: ^7.2.2
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@types/node': ^24.10.0
    eslint: ^9.39.1
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.3
  frontend:
    '@vueuse/core': ^14.0.0
    pinia: ^3.0.4
    vue: ^3.5.24
    vue-draggable-plus: ^0.6.0
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
